#!/bin/bash

fun_socks() {
	clear
	banner_info "            SOCKS PROXY YÖNETİMİ            "
	echo ""
	[[ $(netstat -nplt | grep -wc 'python3') != '0' ]] && {
		sks='\033[1;32mON'
		color_echo_n "PORTLAR: " "yellow"
		color_echo "$(netstat -nplt | grep 'python3' | awk {'print $4'} | cut -d: -f2 | xargs)" "green"
	} || {
		red_code=$(get_color_code "red")
		sks="${red_code}OFF"
	}
	green_code=$(get_color_code "green")
	red_code=$(get_color_code "red")
	[[ $(screen -list | grep -wc 'proxy') != '0' ]] && var_sks1="${green_code}◉" || var_sks1="${red_code}○"
	echo ""
	menu_option "1" "SOCKS SSH $var_sks1" "red" "yellow"
	menu_option "2" "PORT AÇ" "red" "yellow"
	menu_option "3" "DURUMU DEĞİŞTİR" "red" "yellow"
	menu_option "0" "GERİ" "red" "yellow"
	echo ""
	color_echo_n "LÜTFEN SEÇENEKLERDEN BİRİNİ SEÇİN " "green"
	color_echo_n "?" "yellow"
	color_echo_n " " "white"
	read resposta
	if [[ "$resposta" = '1' ]]; then
		if ps x | grep -w proxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
			clear
			banner_danger "             SOCKS PROXY              "
			echo ""
			fun_socksoff() {
				for pidproxy in $(screen -ls | grep ".proxy" | awk {'print $1'}); do
					screen -r -S "$pidproxy" -X quit
				done
				[[ $(grep -wc "proxy.py" /etc/autostart) != '0' ]] && {
					sed -i '/proxy.py/d' /etc/autostart
				}
				sleep 1
				screen -wipe >/dev/null
			}
			color_echo "SOCKS PROXY DEVRE DIŞI BIRAKILIYOR" "green"
			echo ""
			fun_bar 'fun_socksoff'
			echo ""
			msg_ok "SOCKS PROXY BAŞARIYLA DEVRE DIŞI BIRAKILDI!"
			sleep 3
			fun_socks
		else
			clear
			banner_info "             SOCKS PROXY              "
			echo ""
			echo -ne "\033[1;32mHANGİ PORTU KULLANMAK İSTİYORSUNUZ \033[1;33m?\033[1;37m: "
			read porta
			[[ -z "$porta" ]] && {
				echo ""
				msg_err "Geçersiz port!"
				sleep 3
				clear
				fun_connections
			}
			verif_ptrs $porta
			fun_inisocks() {
				sleep 1
				screen -dmS proxy python3 /etc/SSHPlus/proxy.py $porta
				[[ ! -e /etc/autostart ]] && echo '#!/bin/bash' >/etc/autostart
				[[ $(grep -wc "proxy.py" /etc/autostart) = '0' ]] && {
					echo -e "netstat -tlpn | grep -w $porta > /dev/null || screen -dmS proxy python3 /etc/SSHPlus/proxy.py $porta" >>/etc/autostart
				} || {
					sed -i '/proxy.py/d' /etc/autostart
					echo -e "netstat -tlpn | grep -w $porta > /dev/null || screen -dmS proxy python3 /etc/SSHPlus/proxy.py $porta" >>/etc/autostart
				}
				chmod +x /etc/autostart
			}
			echo ""
			echo -e "\033[1;32mSOCKS PROXY BAŞLATILIYOR\033[1;33m"
			echo ""
			fun_bar 'fun_inisocks'
			echo ""
			msg_ok "SOCKS BAŞARIYLA ETKİNLEŞTİRİLDİ"
			sleep 3
			fun_socks
		fi
	elif [[ "$resposta" = '2' ]]; then
		if ps x | grep proxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
			sockspt=$(netstat -nplt | grep 'python3' | awk {'print $4'} | cut -d: -f2 | xargs)
			clear
			echo -e "\E[44;1;37m            SOCKS PROXY            \E[0m"
			echo ""
			echo -e "\033[1;33mKULLANIMDAKİ PORTLAR: \033[1;32m$sockspt"
			echo ""
			echo -ne "\033[1;32mHANGİ PORTU KULLANMAK İSTİYORSUNUZ \033[1;33m?\033[1;37m: "
			read porta
			[[ -z "$porta" ]] && {
				echo ""
				msg_err "Geçersiz port!"
				sleep 2
				clear
				fun_connections
			}
			verif_ptrs $porta
			echo ""
			echo -e "\033[1;32m$porta PORTUNDA SOCKS PROXY BAŞLATILIYOR\033[1;33m"
			echo ""
			abrirptsks() {
				sleep 1
				screen -dmS proxy python3 /etc/SSHPlus/proxy.py $porta
				sleep 1
			}
			fun_bar 'abrirptsks'
			echo ""
			echo -e "\033[1;32mSOCKS PROXY BAŞARIYLA ETKİNLEŞTİRİLDİ\033[1;33m"
			sleep 2
			fun_socks
		else
			clear
			echo -e "\033[1;31mİŞLEV KULLANILAMIYOR\n\n\033[1;33mÖNCE SOCKS'U ETKİNLEŞTİRİN !\033[1;33m"
			sleep 2
			fun_socks
		fi
	elif [[ "$resposta" = '3' ]]; then
		if ps x | grep -w proxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
			clear
			msgsocks=$(cat /etc/SSHPlus/proxy.py | grep -E "MSG =" | awk -F = '{print $2}' | cut -d "'" -f 2)
			echo -e "\E[44;1;37m             SOCKS PROXY             \E[0m"
			echo ""
			color_echo_n "DURUM: " "yellow"
			color_echo "$msgsocks" "green"
			echo""
			echo -ne "\033[1;32mDURUMUNUZU BELİRTİN\033[1;31m:\033[1;37m "
			read msgg
			[[ -z "$msgg" ]] && {
				echo ""
				msg_err "Geçersiz durum!"
				sleep 2
				fun_connections
			}
			[[ ${msgg} != ?(+|-)+([a-zA-Z0-9-. ]) ]] && {
				echo ""
				msg_warn "[!] ÖZEL KARAKTERLERDEN KAÇININ"
				sleep 2
				fun_socks
			}
			show_color_menu
			color_echo_n "BİR RENK SEÇİN" "green"
			color_echo_n " ?" "red"
			color_echo_n " : " "white"
			read sts_cor
			if [[ "$sts_cor" = "1" ]] || [[ "$sts_cor" = "01" ]]; then
				cor_sts='blue'
			elif [[ "$sts_cor" = "2" ]] || [[ "$sts_cor" = "02" ]]; then
				cor_sts='green'
			elif [[ "$sts_cor" = "3" ]] || [[ "$sts_cor" = "03" ]]; then
				cor_sts='red'
			elif [[ "$sts_cor" = "4" ]] || [[ "$sts_cor" = "04" ]]; then
				cor_sts='yellow'
			elif [[ "$sts_cor" = "5" ]] || [[ "$sts_cor" = "05" ]]; then
				cor_sts='#F535AA'
			elif [[ "$sts_cor" = "6" ]] || [[ "$sts_cor" = "06" ]]; then
				cor_sts='cyan'
			elif [[ "$sts_cor" = "7" ]] || [[ "$sts_cor" = "07" ]]; then
				cor_sts='#FF7F00'
			elif [[ "$sts_cor" = "8" ]] || [[ "$sts_cor" = "08" ]]; then
				cor_sts='#9932CD'
			elif [[ "$sts_cor" = "9" ]] || [[ "$sts_cor" = "09" ]]; then
				cor_sts='black'
			elif [[ "$sts_cor" = "10" ]]; then
				cor_sts='null'
			else
				echo -e "\n\033[1;33mGEÇERSİZ SEÇENEK !"
				cor_sts='null'
			fi
			fun_msgsocks() {
				msgsocks2=$(cat /etc/SSHPlus/proxy.py | grep "MSG =" | awk -F = '{print $2}')
				sed -i "s/$msgsocks2/ '$msgg'/g" /etc/SSHPlus/proxy.py
				sleep 1
				cor_old=$(grep 'color=' /etc/SSHPlus/proxy.py | cut -d '"' -f2)
				sed -i "s/\b$cor_old\b/$cor_sts/g" /etc/SSHPlus/proxy.py

			}
			echo ""
			color_echo "DURUM DEĞİŞTİRİLİYOR!" "green"
			echo ""
			fun_bar 'fun_msgsocks'
			restartsocks() {
				if ps x | grep proxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
					echo -e "$(netstat -nplt | grep 'python3' | awk {'print $4'} | cut -d: -f2 | xargs)" >/tmp/Pt_sks
					for pidproxy in $(screen -ls | grep ".proxy" | awk {'print $1'}); do
						screen -r -S "$pidproxy" -X quit
					done
					screen -wipe >/dev/null
					_Ptsks="$(cat /tmp/Pt_sks)"
					sleep 1
					screen -dmS proxy python3 /etc/SSHPlus/proxy.py $_Ptsks
					rm /tmp/Pt_sks
				fi
			}
			echo ""
			color_echo "SOCKS PROXY YENİDEN BAŞLATILIYOR!" "green"
			echo ""
			fun_bar 'restartsocks'
			echo ""
			msg_ok "DURUM BAŞARIYLA DEĞİŞTİRİLDİ!"
			sleep 2
			fun_socks
		else
			clear
			echo -e "\033[1;31mİŞLEV KULLANILAMIYOR\n\n\033[1;33mÖNCE SOCKS SSH'İ ETKİNLEŞTİRİN !\033[1;33m"
			sleep 2
			fun_socks
		fi
	elif [[ "$resposta" = '0' ]]; then
		echo ""
		echo -e "\033[1;31mGeri dönülüyor...\033[0m"
		sleep 1
		fun_connections
	else
		echo ""
		msg_err "Geçersiz seçenek !"
		sleep 1
		fun_socks
	fi

}

